CALLBACK_BALANCE_NAME = 'BL'
CALLBACK_BALANCE_DATA = CALLBACK_BALANCE_NAME + '#{user_id}'

CALLBACK_TOPUP_NAME = 'TU'
CALLBACK_TOPUP_DATA = CALLBACK_TOPUP_NAME + '#{user_id}'

CALLBACK_PAYTABLE_NAME = 'PAYTABLE'
CALLBACK_PAYTABLE_DATA = CALLBACK_PAYTABLE_NAME

CALLBACK_MAKEBET_NAME = 'MB'
CALLBACK_MAKEBET_DATA = CALLBACK_MAKEBET_NAME + '#{callback_id}'

CALLBACK_CANCELBET_NAME = 'CB'
CALLBACK_CANCELBET_DATA = CALLBACK_CANCELBET_NAME + '#{callback_id}'

CALLBACK_CHOOSEAMOUNT_NAME = 'CA'
CALLBACK_CHOOSEAMOUNT_DATA = CALLBACK_CHOOSEAMOUNT_NAME + '#{callback_id}'

CALLBACK_MAKESPIN_NAME = 'MS'
CALLBACK_MAKESPIN_DATA = CALLBACK_MAKESPIN_NAME + '#{callback_id}'

CALLBACK_CLOSESESSION_NAME = 'CS'
CALLBACK_CLOSESESSION_DATA = CALLBACK_CLOSESESSION_NAME + '#{callback_id}'
